---
#rabbitmq的持久卷
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mq-data
  labels:
    pv: pv-mq-data 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 10.10.10.21 #这里请写nfs服务器的ip
    path: /data/volumes/rabbitmq
