---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mq-data
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: pv-mq-data
